apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus 
    access: proxy
    editable: true
    # isDefault: true
    url: http://prometheus:9090
    version: 1

  - name: k6influxdb
    access: proxy
    type: influxdb
    database: k6
    url: http://skeleton-influxdb-1:8086
    isDefault: true
    version: 1

  - name: Jaeger
    type: jaeger
    access: proxy
    editable: true
    url: http://jaeger:14250